export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL";
export const SHOW_CONFIRM_MODAL = "SHOW_CONFIRM_MODAL";
export const SHOW_UTILITY_MODAL = "SHOW_UTILITY_MODAL";
export const SHOW_PROCESSING_WINDOW = "SHOW_PROCESSING_WINDOW";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CONFIRM_MODAL = "CONFIRM_MODAL";
