export const ADD_FAVORITE_ITEM = "ADD_FAVORITE_ITEM";
export const DELETE_FAVORITE_ITEM = "DELETE_FAVORITE_ITEM";
export const ADD_USERLIST = "ADD_USERLIST";
export const DELETE_USERLIST = "DELETE_USERLIST";
