export const FETCH_LOADING_START = "FETCH_LOADING_START";
export const FETCH_FINISHED_SUCCESS = "FETCH_FINISHED_SUCCESS";
export const SET_USER_LISTS = "SET_USER_LISTS";
export const SET_FAVORITED_MOVIES = "SET_FAVORITED_MOVIES";
export const SET_RATED_MOVIES = "SET_RATED_MOVIES";
